Cactooz/StarWarsWiki

starwarswiki/src/presenters/detailsPresenter.jsx
starwarswiki/src/utilities.js
starwarswiki/src/views/detailsView.jsx

- Moved URL parsing and data fetching to utilities.js
- Removed unused functions
- Removed "you may also like" section from details view and presenter. It should be in a different view
- Added suspense when a page is loading
Test functionality by going to ```/characters``` and clicking any character. Suspense will show before fetch is complete and related cards will be gone.

Cleanup details page, add utilities

---

starwarswiki/src/App.jsx
starwarswiki/src/models/model.js
starwarswiki/src/presenters/landingPagePresenter.jsx
starwarswiki/src/presenters/searchBarPresenter.jsx
starwarswiki/src/presenters/searchPresenter.jsx
starwarswiki/src/views/browseView.jsx
starwarswiki/src/views/landingPageView.jsx
starwarswiki/src/views/searchBarView.jsx

- Reformat and add search path in App.jsx
- Add search results to model
- Move the search bar presenter to landing page presenter
- Fix so pressing enter will search for the autocomplete suggestions 
- Add a search presenter that shows search results
- Reformat browse view
1. Navigate to the landing page
2. Type something in the search bar
3. Press enter when results are showing otherwise an empty search will be done (Read room for improvements)
4. You will now navigate to the search page
5. You can interact with the cards or do another search
If you search faster than the results appear, you will do an empty search. According to me, this is not an error, but rather a bad user experience. This is hard since the API does not offer a search function and the autocomplete is a 3rd party …

Improve search function

---

starwarswiki/src/models/firebaseModel.js
starwarswiki/src/models/model.js

- Added per-user persistence to Firebase
- Added listener to fetch data when Firebase updates
1. Login to your Google account
2. Open new browser tab. You should see your favorite list there as well
3. Log in on another browser. Your favorites should be there as well
4. Try adding and removing favorites to see the list update
Don't save image source and id to the database, to save Firebase storage. Instead, fetch the necessary data from the APIs using the name and path.

Persistence

---

starwarswiki/src/App.jsx
starwarswiki/src/models/firebaseModel.js
starwarswiki/src/models/model.js
starwarswiki/src/presenters/detailsPresenter.jsx
starwarswiki/src/presenters/moreDetailsPresenter.jsx
starwarswiki/src/views/moreDetailsView.jsx

Add an extra view to all details view that shows more data about the character/location/vehicle.
It gets the hashdata from Firebase and maps our two APIs together.
- MoreDetailsPresenter
- MoreDetailsView
- (Hashdata on Firebase)
1. Go onto a page that has moreDetails, such as Luke, Yoda, Naboo, X-Wing
2. See if more details load at the bottom of the page
3. Go to another page that doesn't have more data.
4. Check if no data is shown.
- Update the MoreDetailsView with better CSS.
- Show the key and values with the first letter capitalized.
- Make a layout for the details views that include the header, details and moreDetails to make it more DRY.

Add MoreDetailsView

---

starwarswiki/src/main.jsx
starwarswiki/src/models/firebaseModel.js
starwarswiki/src/models/model.js
starwarswiki/src/views/browseView.jsx

Model was previously aware of persistence. Now everything except the setter for the favorites is handled in firebaseModel.js
- Added reaction side-effect to detect changes to model in main.jsx
- Bouncing detection when writing to DB
- Changed the saved data in browseView to be consistent with other views
- Minor fixes

Model persistence

---

starwarswiki/src/presenters/moreDetailsPresenter.jsx

Closes #53
- Fixed suspense while loading moreDetails from SWAPI
- Fixed moreDetailsView not updating fast enough
Go to any character with more details, e.g. `Anakin Skywalker`. Then go to another with more details in a different category, e.g. `X-wing Starfighter`. Suspense should show and details should update accordingly, without Anakin's details showing initially like they did before. Now go to `4-LOM` who doesn't have more details. Suspense should show before 'Your eyes can deceive you; don't trust them.' shows. Everything should work from either search bar or browse.

Show suspense while loading moreDetails

---

starwarswiki/src/fetch.js

Add catch when fetching data from the APIs. An error occurred when refreshing the browse views several times. An error was thrown that said that the 'Request aborted'. The error was not breaking the site, but now we have some handling of the error.
- Added catch in `fetchApi` in `fetch.js`
- Reformatted `fetch.js`

Catch axios error, reformat

---

starwarswiki/src/models/model.js

When refreshing the details view multiple times errors were thrown because `model.details` was `undefined`. Added check to fix this in the model. Also made some formatting when saving the file.

Details bug

---

starwarswiki/src/presenters/searchPresenter.jsx

Closes #82 
Previously, the favorite limit was not passed to `browseView` from the `searchPresenter`. Thus, it was possible to exceed the favorite limit. I added one line to fix this.
Test by going to the search view and try to add favorites when you have reached the limit. Toast should show saying that the limit is reached.

Fix favorite limit in searchView

---

starwarswiki/src/presenters/moreDetailsPresenter.jsx

Fixes #78 
Removed 'More Details' header. Kept it in a `<div>` to render it below the detail's spinner.

Remove more details header

---

starwarswiki/src/models/model.js
starwarswiki/src/presenters/profilePresenter.jsx
starwarswiki/src/views/friendSidebarView.jsx
starwarswiki/src/views/profileView.jsx

- Reformatted files
- Removed `setCustomMessage` function
- Added toasts instead of messages when adding friends
- Copy the ID to clipboard when clicking `Click to show your ID`. Added toast as feedback
- Changed behavior when adding a friend that has already sent you a friend request. Now you accept the incoming request instead
- Did some rewording in the messages and headers
- Changed tags in `friendSidebarView` for easier styling
A unique toast should show for the following:
- Adding yourself to your friends
- Sending a friend request
- Sending a friend request multiple times to the same user
- Accepting a friend request
- Sending a friend request to a friend that has already sent you a request. Friend should also be added
- Adding a non-existing ID
- Adding a friend that is already on …

Toastify profile messages

---

starwarswiki/src/style/style.scss
starwarswiki/src/views/landingPageView.jsx

- Added styling to the main title on the landing page, it should get smaller for small screen sizes (less than 800px).
- Halved the header & nav padding.
- Made landing page card text smaller.
Fixes #95

Main title and header styling

---

starwarswiki/src/components/Card.jsx
starwarswiki/src/components/LandingCard.jsx
starwarswiki/src/views/detailsView.jsx
starwarswiki/src/views/landingPageView.jsx

Added alt text that describes all images on the website. 
The browse/details only show the name of the character, since we can't generate better alt text for them. But the landing page has better alt text descriptions.
Go onto the landing page, browse view and details view and inspect the images. They should now have the `alt` attribute inside of them with the correct text.

Add alt text to all images

---

starwarswiki/src/presenters/detailsPresenter.jsx
starwarswiki/src/presenters/moreDetailsPresenter.jsx

Fixes #104 
Add 404 when going to an invalid details URL. This also fixes a bug in the hamburger.
Go to an invalid URL `/vehicles/Yoda`. 404 should show. Then go to `/characters/Yoda`. Should work as normal. Go to a character without more details, i.e `/characters/Admiral Ozzel`. More details should show quote as before.

404 details

---

starwarswiki/src/presenters/browsePresenter.jsx
starwarswiki/src/presenters/detailsPresenter.jsx
starwarswiki/src/presenters/landingPagePresenter.jsx
starwarswiki/src/presenters/profilePresenter.jsx
starwarswiki/src/presenters/searchPresenter.jsx

- Some undefined checks in browse presenter
- Add useEffect with empty array as dependency that scroll to top. Meaning when the component is rendered for the first time, scroll to top.
- Browse pages should always start at top (Characters, Vehicles, Locations, Search)
- Landing page should always start at top
- Profile page should always start at top
- Details page should always start at top

Scroll to top

---

starwarswiki/src/components/Card.jsx

Alt text was showing when loading cards, which was ugly and distracting. The alt text was the same as the card title, which made it redundant. Removed it as it made no difference for screen readers.

Remove redundant alt text

---

starwarswiki/src/presenters/detailsPresenter.jsx
starwarswiki/src/presenters/headerPresenter.jsx
starwarswiki/src/presenters/searchPresenter.jsx
starwarswiki/src/views/searchBarView.jsx

- Update text when no search results (Added  "Try again by typing in the search box")
- Clear the search box after a search to not confuse the user that they can search again
- Exit search box after search (On mobile the keyboard collapses)
- Free text search (Typing for example "Skywalker" and pressing enter)
- Select an option by mouse click (Type "Skywal" and click! on Luke Skywalker)
- Select an option by pressing enter (Type "Skywal" and use arrow keys and press enter on Luke Skywalker)
During the third test, you will notice the search options appearing again quickly before disappearing. This is due to my hacky fix of free search and I do not know how to fix it right now.

Improve Search

---

starwarswiki/src/presenters/moreDetailsPresenter.jsx
starwarswiki/src/style/style.scss

Fixes #109 
Added a line that “explains” the quote when no more details are found. This was needed after user complaints, thinking that the site was bugged, as the same quote showed everywhere.

Change more details view

---

starwarswiki/package.json
starwarswiki/src/components/EmblaCarousel.jsx
starwarswiki/src/components/LandingCard.jsx
starwarswiki/src/models/firebaseModel.js
starwarswiki/src/models/model.js
starwarswiki/src/presenters/landingPagePresenter.jsx
starwarswiki/src/style/embla.scss
starwarswiki/src/style/style.scss
starwarswiki/src/style/variables.scss
starwarswiki/yarn.lock

- Installed embla-carousel-autoplay & embla-carousel-react
- Add a carousel with recommended items 
- Download 3 random characters, 3 random vehicles and 3 random locations from the SWAPI hash on firebase. (So all of them will have more details when you click on them)
- `yarn install`
- `yarn dev`
- Check if the carousel has a loading hologram effect
- Check that all items go to the correct page (especially Palpatine)
- Check if you can drag the carousel
- Check if you can use the buttons
- Check if it auto plays by default
- Check it on mobile as well

Add embla carousel at landing page

---

starwarswiki/src/presenters/searchPresenter.jsx
starwarswiki/src/views/noResultsView.jsx

- Make the no search results text a view to follow MVP.
I don't think this is necessary, but this way there should be no question marks that MVP.

Make no search results text a view
