starwarswiki/src/views/browseView.jsx
=> Browse view

starwarswiki/src/components/Card.jsx, starwarswiki/src/views/browseView.jsx
=> Make card component

starwarswiki/src/components/LandingCard.jsx, starwarswiki/src/style.css, starwarswiki/src/views/landingPageView.jsx
I created a landing card component and a landing page with three cards. This is not the final product!!
=> Add mockup landing page.

starwarswiki/src/components/Card.jsx, starwarswiki/src/views/browseView.jsx
Fix so native event works fine!
=> Fix so card native event works

starwarswiki/src/App.jsx, starwarswiki/src/components/LandingCard.jsx, starwarswiki/src/presenters/landingPagePresenter.jsx, starwarswiki/src/style.css, starwarswiki/src/views/landingPageView.jsx
Implemented a simple landing page with navigation and responsive cards.
=> Landing page

.vscode/settings.json, starwarswiki/package.json, starwarswiki/src/fetch.js, starwarswiki/src/main.jsx, starwarswiki/yarn.lock
Fetch functions for fetchSWAPI & fetchSWDatabank parsing the response and returning it as `{loading, error, data}`.
Added react-query & axios packages.
Test by calling fetchSWAPI & fetchSWDatabank with a path like `charcters/name/Luke%20Skywalker` and params like an object `{page: 0, limit: 3}`.
Make sure to do `yarn install` before running.
=> Add fetch function for SWAPI & SWD

starwarswiki/src/App.jsx, starwarswiki/yarn.lock
Add navigation in the router using wildcards.
=> Navigation

starwarswiki/src/App.jsx, starwarswiki/src/presenters/errorPresenter.jsx, starwarswiki/src/views/errorView.jsx
Make all invalid pages go to a 404 page
=> Add 404 page

starwarswiki/src/App.jsx, starwarswiki/src/presenters/footerPresenter.jsx, starwarswiki/src/views/footerView.jsx
Add a static footer that is always shown.
=> Add static footer

starwarswiki/src/fetch.js, starwarswiki/src/model.js, starwarswiki/src/presenters/browsePresenter.jsx
saves data into model
uses queryclient to fetch queries
=> Save fetch into model

starwarswiki/src/App.jsx, starwarswiki/src/presenters/headerPresenter.jsx, starwarswiki/src/style.css, starwarswiki/src/views/headerView.jsx
Add header to the necessary paths. 
Header is shown at all pages except the landing page.
=> Add header

starwarswiki/src/components/Card.jsx, starwarswiki/src/presenters/browsePresenter.jsx, starwarswiki/src/views/browseView.jsx
Added eventlistener for browser back arrow that resets the currently loaded data in browseView
=> Reset data on back button browse

utils/fetchAll.js
Used to get all data from SWD. Use with caution in the normal `fetch.js` file.
=> Add function to get all API data

starwarswiki/src/models/model.js, starwarswiki/src/presenters/browsePresenter.jsx
add infinite scroll to browse page
=> Infinite scroll

starwarswiki/src/presenters/searchPresenter.jsx, starwarswiki/src/views/browseView.jsx
A line got removed when doing #45
Sorry for that, don't know why
Should be fixed now
=> Fix favorite button

starwarswiki/src/components/Card.jsx, starwarswiki/src/models/model.js
Replace all "/" with "%2F" and all "." with "%2E" to work correctly with API
1. Navigate to landing page
2. Type "Palpatine"
3. Press enter when options appear
=> Fix "." and "/" in free text search

starwarswiki/src/presenters/moreDetailsPresenter.jsx
=> Fix n/a and none to not show up in moreDetails

starwarswiki/src/fetch.js, starwarswiki/src/models/model.js, starwarswiki/src/presenters/browsePresenter.jsx
First load is now fetching 4 pages, scroll is new fetching 3 pages
=> Fetch more pages

starwarswiki/src/presenters/moreDetailsPresenter.jsx
=> Check remove "N/A" values from more details

starwarswiki/package.json, starwarswiki/src/AnimatedRoutes.jsx, starwarswiki/src/App.jsx, starwarswiki/src/models/model.js, starwarswiki/src/presenters/headerPresenter.jsx, starwarswiki/src/views/browseView.jsx, starwarswiki/yarn.lock
- Add framer motion (The animation library)
- Rewrite the router to work with framer motion
- Split the routes into a file called AnimatedRoutes (This is where the animations are configured)
- Add a fade animation when navigating between routes (The animation itself can be changed, duration etc)
- Add search string to model so that every search has a unique path
1. Run yarn install
2. Navigate the webpage to see the fade animations
3. Everything that worked before should still work
=> Router animate

starwarswiki/src/models/model.js, starwarswiki/src/presenters/browsePresenter.jsx
Added some logic to make sure that data can not be undefined
=> Fix browse view errors

starwarswiki/src/models/firebaseModel.js, starwarswiki/src/presenters/profilePresenter.jsx, starwarswiki/src/views/profileView.jsx
Fixes #75 
- Removed profile picture from `profileView`
- Added check in `firebaseModel.js` to see if data is loading
- Profile is now rendered when favorites are have finished loading from Firebase. Suspense while waiting
- Changed the wording in the profile greeting and in the header for the favorite list
- Reformatted `profilePresenter`
=> Profile suspense

starwarswiki/vite.config.js
Update build settings to not have minified code after build.
=> Update build settings to not minify code

starwarswiki/src/fetch.js
#74 was deleted in #89 . These changes fixes this. Reformatted `fetch` and added catch.
=> Reformat, add catch

starwarswiki/src/style/variables.scss, starwarswiki/src/views/navbarView.jsx
Fix images missing after build.
Fixed in header navbar and variables styling.
=> Fix image not getting built

starwarswiki/src/AnimatedRoutes.jsx, starwarswiki/src/components/Card.jsx, starwarswiki/src/components/GoToProfile.jsx, starwarswiki/src/components/LandingCard.jsx, starwarswiki/src/models/model.js, starwarswiki/src/presenters/browsePresenter.jsx, starwarswiki/src/presenters/headerPresenter.jsx, starwarswiki/src/presenters/landingPagePresenter.jsx, starwarswiki/src/presenters/profilePresenter.jsx, starwarswiki/src/presenters/searchPresenter.jsx, starwarswiki/src/views/browseView.jsx, starwarswiki/src/views/landingPageView.jsx, starwarswiki/src/views/navbarView.jsx, starwarswiki/src/views/profileView.jsx
- Add animation state to model
- Check animation state in all <Link> components
- Reformat browsePresenter (A.K.A Ctrl + s)
1. The bug  #76 was that if you spam on a character from browse view the URL broke. This is now fixed.
2. Another problem I noticed was that when you spam on a card, the history gets updated for every click. If you managed to click a card 3 times during the animation, you could press the back arrow 3 times. This should also be fixed.
If you spam from the landing page when the characters are cached. So you spam click characters and then directly spam for example Hyper Rod, the history will be duplicated.
=> 76 double click card bug

starwarswiki/src/style/style.scss, starwarswiki/src/views/detailsView.jsx
Add category to details view to distinguish what the page is for better UX, after user feedback. Added some styling.
=> Add category to details

starwarswiki/package.json, starwarswiki/src/App.jsx, starwarswiki/src/components/GoToProfile.jsx, starwarswiki/src/models/model.js, starwarswiki/src/presenters/headerPresenter.jsx, starwarswiki/src/style/burgermenu.scss, starwarswiki/src/style/style.scss, starwarswiki/src/views/hamburgerView.jsx, starwarswiki/src/views/navbarView.jsx, starwarswiki/yarn.lock
- Add react-hamburger-menu component
- Add a hamburger menu on small screens
- Run yarn install
- Test on phone (yarn run dev --host)
- Test on phone layout using your browsers inspect tool
- Navigate using the hamburger menu
- Menu should close when pressing a link
=> Hamburger menu

starwarswiki/src/components/Card.jsx, starwarswiki/src/components/SignOutButton.jsx, starwarswiki/src/presenters/profilePresenter.jsx, starwarswiki/src/style/style.scss, starwarswiki/src/style/variables.scss, starwarswiki/src/views/friendSidebarView.jsx, starwarswiki/src/views/profileView.jsx
- Add styling to the profile page.
- Different colored buttons for X and Check.
- Changed the text that is showed on other peoples profiles.
- Add titles to all buttons/links so a popup is shown on hover.
- Fixed so the favorites title is only shown if the profile has any favorites.
- Check others profiles with and without favorites.
- Try to add, get and accept friend requests.
- Remove all your favorites and check how it looks.
=> Friends profile styling

starwarswiki/src/presenters/searchPresenter.jsx
Forgot to import useEffect in #106, whoops!
=> Import useEffect on search

starwarswiki/package.json, starwarswiki/src/App.jsx, starwarswiki/src/components/StarrySky.jsx, starwarswiki/src/main.jsx, starwarswiki/src/style/style.scss, starwarswiki/yarn.lock
Added dynamic background for nicer UI after user feedback. Resizing the browser will cause some flickering as the viewport changes. Shouldn't be a problem for most users. Add epileptic warning?
Test by running `yarn install` and then going to the different pages on the site. Resize the window and see the stars adapt to the new window. Test on mobile as well. There, resizing shouldn't be a concern, even when the browser UI changes. Limited the stars to 100 to keep performance impact low.
=> Dynamic background

starwarswiki/src/components/StarrySky.jsx, starwarswiki/src/style/style.scss
Added blur and gradient to stars. Now less eye-catching. Same testing as in #108
=> Blur stars

starwarswiki/src/AnimatedRoutes.jsx, starwarswiki/src/App.jsx, starwarswiki/src/components/StarrySky.jsx, starwarswiki/src/style/style.scss
- Force the footer to be at the bottom. (Fixes #110)
- Update star blink and fall time.
=> Force footer to bottom & update star blink delay

starwarswiki/src/components/GoToProfile.jsx, starwarswiki/src/presenters/headerPresenter.jsx, starwarswiki/src/style/burgermenu.scss, starwarswiki/src/style/style.scss, starwarswiki/src/views/hamburgerView.jsx, starwarswiki/src/views/navbarView.jsx
Updates:
- You can no longer click a navbar or hamburger link to current page.
After some styling, we can hopefully close #71
=> Header active page no longer clickable

starwarswiki/src/AnimatedRoutes.jsx, starwarswiki/src/components/GoToProfile.jsx, starwarswiki/src/presenters/landingPagePresenter.jsx, starwarswiki/src/style/embla.scss, starwarswiki/src/style/style.scss, starwarswiki/src/views/hamburgerView.jsx, starwarswiki/src/views/navbarView.jsx
- Fix details view to wrap more details below normal details
- Fix main margin-top to get updated onload and onresize.
- All text should now have the default pointer.
- Remove extra p tags from inside of Link a tags in nav and hamburger menu.
=> Fix styling

starwarswiki/src/presenters/moreDetailsPresenter.jsx
Fix items with more details that have all data as undefined, N/A etc that get filtered away returns nothing found instead of an empty array.
- Check that Aleen gets no data found instead of empty box
=> All more details is filtered render nothing found

starwarswiki/src/main.jsx, starwarswiki/src/presenters/profilePresenter.jsx, starwarswiki/src/views/browseView.jsx, starwarswiki/src/views/detailsView.jsx, starwarswiki/src/views/friendSidebarView.jsx
When favorites limit was reached you could still add favorites from a friends profile. This is now fixed. 
Removed Toastify component from each individual view and added it to the root component instead.
=> Fix fav bug

starwarswiki/index.html, starwarswiki/src/components/Card.jsx, starwarswiki/src/components/EmblaCarousel.jsx, starwarswiki/src/components/GoToProfile.jsx, starwarswiki/src/components/LandingCard.jsx, starwarswiki/src/main.jsx, starwarswiki/src/models/firebaseModel.js, starwarswiki/src/style/burgermenu.scss, starwarswiki/src/style/embla.scss, starwarswiki/src/style/style.scss, starwarswiki/src/style/variables.scss, starwarswiki/src/views/browseView.jsx, starwarswiki/src/views/detailsView.jsx, starwarswiki/src/views/friendSidebarView.jsx, starwarswiki/src/views/landingPageView.jsx, starwarswiki/src/views/moreDetailsView.jsx, starwarswiki/src/views/profileView.jsx, starwarswiki/vite.config.js
- Added meta tags.
- Changed some `<div>`'s to `<section>`'s for better accessability.
- Removed model from window.
- Fixed firebase model to use reactiveModel instead of model.
- Fixed double conditional check in friends view and combined then (fixed CSS due to that).
- Add sign in button if you are not signed in on the profile page.
- Add big-margin and small-margin instead of calculating the small-margin a lot of times.
- Check that everything works
- Especially the friends page
=> Final changes

starwarswiki/src/models/firebaseModel.js
Revert changes made to getPreview in firebaseModel as the change caused an error.
=> Fix error in getPreview

starwarswiki/src/style/embla.scss
- Max out embla at 80% of window width and at max 3000px
=> Limit embla size to screen size
